name: Cache deps
description: Cache dependencies
inputs:
  caching:
    description: determine whether to cache or not
    required: false
    default: "true"
outputs:
  installed-dependencies:
    description: Whether dependencies are installed or used from cache
    value: ${{ steps.set-output.outputs.installed }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v5
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
    - name: Set output based on install outcome
      id: set-output
      # if: always()
      run: |
        if [ "${{ steps.install.outcome }}" == "success" ]; then
          echo "installed=true" >> $GITHUB_OUTPUT
        else
          echo "installed=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Display caching value
      run: echo "Caching is set to ${{ inputs.caching }}"
      shell: bash
