name: Cache deps
description: Cache dependencies
inputs:
  caching:
    description: determine whether to cache or not
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v5
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || !inputs.caching
      run: npm ci
      shell: bash
